# Generated by pip2nix 0.6.0.dev1
# See https://github.com/johbo/pip2nix

{
  Babel = super.buildPythonPackage {
    name = "Babel-2.3.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pytz];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6e/96/ba2a2462ed25ca0e651fb7b66e7080f5315f91425a07ea5b34d7c870c114/Babel-2.3.4.tar.gz";
      sha256 = "0x98qqqw35xllpcama013a9788ly84z8dm1w2wwfpxh2710c8df5";
    };
  };
  EXIFRead = super.buildPythonPackage {
    name = "EXIFRead-2.1.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/7b/cb/92b644626830115910cf2b36d3dfa600adbec86dff3207a7de3bfd6c6a60/ExifRead-2.1.2.tar.gz";
      sha256 = "1b90jf6m9vxh9nanhpyvqdq7hmfx5iggw1l8kq10jrs6xgr49qkr";
    };
  };
  Flask = super.buildPythonPackage {
    name = "Flask-0.11.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [Werkzeug Jinja2 itsdangerous click];
    src = fetchurl {
      url = "https://pypi.python.org/packages/55/8a/78e165d30f0c8bb5d57c429a30ee5749825ed461ad6c959688872643ffb3/Flask-0.11.1.tar.gz";
      sha256 = "03kbfll4sj3v5z7r31c7bhfpi11r1np076d4p1k2kg4yzcmkywdl";
    };
  };
  Jinja2 = super.buildPythonPackage {
    name = "Jinja2-2.8";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [MarkupSafe];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f2/2f/0b98b06a345a761bec91a079ccae392d282690c2d8272e708f4d10829e22/Jinja2-2.8.tar.gz";
      sha256 = "1x0v41lp5m1pjix3l46zx02b7lqp2hflgpnxwkywxynvi3zz47xw";
    };
  };
  Lektor = super.buildPythonPackage {
    name = "Lektor-2.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [Jinja2 click watchdog mistune Flask EXIFRead inifile Babel setuptools pip requests];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a0/2c/7dcbda332db0e7ece0e5476c324983fef455e9223e351ff972674fa5bdac/Lektor-2.3.tar.gz";
      sha256 = "14jlazbpsyraci5h40qixbww2kj04wgdxh6d8zm2ap70g5dh8q9v";
    };
  };
  MarkupSafe = super.buildPythonPackage {
    name = "MarkupSafe-0.23";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz";
      sha256 = "1hvip33wva3fnmvfp9x5klqri7hpl1hkgqmjbss18nmrb7zimv54";
    };
  };
  PyYAML = super.buildPythonPackage {
    name = "PyYAML-3.12";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz";
      sha256 = "1aqjl8dk9amd4zr99n8v2qxzgmr2hdvqfma4zh7a41rj6336c9sr";
    };
  };
  Werkzeug = super.buildPythonPackage {
    name = "Werkzeug-0.11.11";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/43/2e/d822b4a4216804519ace92e0368dcfc4b0b2887462d852fdd476b253ecc9/Werkzeug-0.11.11.tar.gz";
      sha256 = "1rgpq8a2qv26d75v9j3b074inirlyy6y4b5x4rxblp202jy4cb77";
    };
  };
  argh = super.buildPythonPackage {
    name = "argh-0.26.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e3/75/1183b5d1663a66aebb2c184e0398724b624cecd4f4b679cb6e25de97ed15/argh-0.26.2.tar.gz";
      sha256 = "0rdv0n2aa181mkrybwvl3czkrrikgzd4y2cri6j735fwhj65nlz9";
    };
  };
  cffi = super.buildPythonPackage {
    name = "cffi-1.9.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pycparser];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a1/32/e3d6c3a8b5461b903651dd6ce958ed03c093d2e00128e3f33ea69f1d7965/cffi-1.9.1.tar.gz";
      sha256 = "1y6s1wczd400w4r0dpg97n0xifiskfjb65rjax8w20ys7zahngjn";
    };
  };
  click = super.buildPythonPackage {
    name = "click-6.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/7a/00/c14926d8232b36b08218067bcd5853caefb4737cda3f0a47437151344792/click-6.6.tar.gz";
      sha256 = "1sggipyz52crrybwbr9xvwxd4aqigvplf53k9w3ygxmzivd1jsnc";
    };
  };
  cryptography = super.buildPythonPackage {
    name = "cryptography-1.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [idna pyasn1 six setuptools cffi];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d7/a2/b90736c37fd720db425c5e48d69da75a6eff6609b22d2123762f1ae8c5f5/cryptography-1.6.tar.gz";
      sha256 = "0gwvmz6w5ml0bjbgmdiscsv5i948lrjd381z7h9qkz6kr398c3ad";
    };
  };
  idna = super.buildPythonPackage {
    name = "idna-2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fb/84/8c27516fbaa8147acd2e431086b473c453c428e24e8fb99a1d89ce381851/idna-2.1.tar.gz";
      sha256 = "0xn60hnmwrxijnq2hnfixmy50cacv1jv2fqngxwx0g5zms0z4dpd";
    };
  };
  inifile = super.buildPythonPackage {
    name = "inifile-0.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/9b/3d/157aee6b7b3c6422c165ff96b5095cb9c4a46916af45bef9133c11cfbfc6/inifile-0.3.tar.gz";
      sha256 = "0zgd53czc1irwx6b5zip8xlmyfr40hz2pd498d8yv61znj6lm16h";
    };
  };
  itsdangerous = super.buildPythonPackage {
    name = "itsdangerous-0.24";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz";
      sha256 = "06856q6x675ly542ig0plbqcyab6ksfzijlyf1hzhgg3sgwgrcyb";
    };
  };
  mistune = super.buildPythonPackage {
    name = "mistune-0.7.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/88/1e/be99791262b3a794332fda598a07c2749a433b9378586361ba9d8e824607/mistune-0.7.3.tar.gz";
      sha256 = "04xpk1zvslhq3xpnf01g3ag0dy9wfv4z28p093r8k49vvxlyil11";
    };
  };
  pathtools = super.buildPythonPackage {
    name = "pathtools-0.1.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz";
      sha256 = "1h7iam33vwxk8bvslfj4qlsdprdnwf8bvzhqh3jq5frr391cadbw";
    };
  };
  pip = super.buildPythonPackage {
    name = "pip-9.0.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz";
      sha256 = "03clr9c1dih5n9c00c592zzvf6r1ffimywkaq9agcqdllzhl7wh9";
    };
  };
  pyOpenSSL = super.buildPythonPackage {
    name = "pyOpenSSL-16.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [cryptography six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0c/d6/b1fe519846a21614fa4f8233361574eddb223e0bc36b182140d916acfb3b/pyOpenSSL-16.2.0.tar.gz";
      sha256 = "0vji4yrfshs15xpczbhzhasnjrwcarsqg87n98ixnyafnyxs6ybp";
    };
  };
  pyasn1 = super.buildPythonPackage {
    name = "pyasn1-0.1.9";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f7/83/377e3dd2e95f9020dbd0dfd3c47aaa7deebe3c68d3857a4e51917146ae8b/pyasn1-0.1.9.tar.gz";
      sha256 = "0zraxni14bqi20kr4bi6nwsh32aibz0fq0xaczfisw0zdpcsqg45";
    };
  };
  pycparser = super.buildPythonPackage {
    name = "pycparser-2.17";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz";
      sha256 = "1dkkjri0miidqb1zcqhqljfa34fcy9k5akasgwsv6k622zlk3b0a";
    };
  };
  pytz = super.buildPythonPackage {
    name = "pytz-2016.7";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1d/ff/84f49d2f318383c634b0709aae6c5671e65f63017a9742dee760fd4d897d/pytz-2016.7.zip";
      sha256 = "0a999wmr2k36snk53gic6846012wnbnzmxl4zwf5fm02s0a9hk85";
    };
  };
  requests = super.buildPythonPackage {
    name = "requests-2.12.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pyOpenSSL cryptography idna];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6e/40/7434b2d9fe24107ada25ec90a1fc646e97f346130a2c51aa6a2b1aba28de/requests-2.12.1.tar.gz";
      sha256 = "0bk1icw64h0502xrllv19011p5vrv3qhyja0w05ri46zjkmfq291";
    };
  };
  setuptools = super.buildPythonPackage {
    name = "setuptools-29.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6f/4f/62e4eb1ff67f8877434b3aaa62298cd0abcac9a73aee44b00249b9bac1f7/setuptools-29.0.0.zip";
      sha256 = "03amvvac464fm926w45g759pdjyvqb7p1dmc514ypa12yqk9dbh5";
    };
  };
  six = super.buildPythonPackage {
    name = "six-1.10.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz";
      sha256 = "0snmb8xffb3vsma0z67i0h0w2g2dy0p3gsgh9gi4i0kgc5l8spqh";
    };
  };
  watchdog = super.buildPythonPackage {
    name = "watchdog-0.8.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [PyYAML argh pathtools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz";
      sha256 = "0qj1vqszxwfx6d1s66s96jmfmy2j94bywxiqdydh6ikpvcm8hrby";
    };
  };

### Test requirements

  
}
