# Generated by pip2nix 0.7.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  affinity = super.buildPythonPackage {
    name = "affinity-0.1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/32/a7/69e207c17b4d7f23f7537f97c2938053e6ba24b6206d1856790d2eb8e4d8/affinity-0.1.0.tar.gz";
      sha256 = "1i6j7kszvnzh5vh9k48cqwx2kzf73a6abgv9s6bf0j2zmfjl2wb6";
    };
  };
  asn1crypto = super.buildPythonPackage {
    name = "asn1crypto-0.24.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fc/f1/8db7daa71f414ddabfa056c4ef792e1461ff655c2ae2928a2b675bfed6b4/asn1crypto-0.24.0.tar.gz";
      sha256 = "0jaf8rf9dx1lf23xfv2cdd5h52f1qr3w8k63985bc35g3d220p4x";
    };
  };
  attrs = super.buildPythonPackage {
    name = "attrs-17.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/3f/a4/d0db68156abbdee228ce69a786ecb512da40b36b1289aadb9e3f9fd45121/attrs-17.3.0.tar.gz";
      sha256 = "0g42ky381yip9hp1b7jhp6bhy8ddq3iwg8n8jy2nvwvw5pim73y7";
    };
  };
  automat = super.buildPythonPackage {
    name = "automat-0.6.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [attrs six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/de/05/b8e453085cf8a7f27bb1226596f4ccf5cc9e758377d60284f990bbdc592c/Automat-0.6.0.tar.gz";
      sha256 = "1a7nsrljysfmdqmpn2apfa1gg6rfah4y9sizvns8gb08rx7d07rw";
    };
  };
  bcrypt = super.buildPythonPackage {
    name = "bcrypt-3.1.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [cffi six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f3/ec/bb6b384b5134fd881b91b6aa3a88ccddaad0103857760711a5ab8c799358/bcrypt-3.1.4.tar.gz";
      sha256 = "13cyrnqwkhc70rs6dg65z4yrrr3dc42fhk11804fqmci9hvimvb7";
    };
  };
  bleach = super.buildPythonPackage {
    name = "bleach-2.1.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six html5lib];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b3/5f/0da670d30d3ffbc57cc97fa82947f81bbe3eab8d441e2d42e661f215baf2/bleach-2.1.2.tar.gz";
      sha256 = "068s5m2j0ydcq5193nvh5cv78zqch8jg7mjmvgc8grx4psz8rz1q";
    };
  };
  blist = super.buildPythonPackage {
    name = "blist-1.3.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/6b/a8/dca5224abe81ccf8db81f8a2ca3d63e7a5fa7a86adc198d4e268c67ce884/blist-1.3.6.tar.gz";
      sha256 = "1hqz9pqbwx0czvq9bjdqjqh5bwfksva1is0anfazig81n18c84is";
    };
  };
  canonicaljson = super.buildPythonPackage {
    name = "canonicaljson-1.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [simplejson frozendict];
    src = fetchurl {
      url = "https://github.com/matrix-org/python-canonicaljson/archive/92e2c06871cc275c2a8b8e3e899141a212aae0e8.tar.gz";
      sha256 = "0pfi3h8bhfv044yhdf4lgbkkzap3nhyyzg1f0jxkjhz4cf3lmgf9";
    };
  };
  certifi = super.buildPythonPackage {
    name = "certifi-2017.11.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz";
      sha256 = "1h0k6sy3p4csfdayghg2wjbnb1hfz27i5qbr0c7v8dhira8l5isy";
    };
  };
  cffi = super.buildPythonPackage {
    name = "cffi-1.11.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pycparser];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c9/70/89b68b6600d479034276fed316e14b9107d50a62f5627da37fafe083fde3/cffi-1.11.2.tar.gz";
      sha256 = "19h0wwz9cww74gw8cyq0izj8zkhjyzjw2d3ks1c3f1y4q28xv1xb";
    };
  };
  chardet = super.buildPythonPackage {
    name = "chardet-3.0.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  constantly = super.buildPythonPackage {
    name = "constantly-15.1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/95/f1/207a0a478c4bb34b1b49d5915e2db574cadc415c9ac3a7ef17e29b2e8951/constantly-15.1.0.tar.gz";
      sha256 = "0dgwdla5kfpqz83hfril716inm41hgn9skxskvi77605jbmp4qsq";
    };
  };
  cryptography = super.buildPythonPackage {
    name = "cryptography-2.1.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [idna asn1crypto six cffi enum34 ipaddress];
    src = fetchurl {
      url = "https://pypi.python.org/packages/78/c5/7188f15a92413096c93053d5304718e1f6ba88b818357d05d19250ebff85/cryptography-2.1.4.tar.gz";
      sha256 = "14aj5ipbj1w5kba2hv6323954pachhflfrjhhmkjwssv3hvngng4";
    };
  };
  daemonize = super.buildPythonPackage {
    name = "daemonize-2.4.7";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/84/15/923e3fe48239adf5d697c29e04a3f868d3e4ce8539aab29d6abe784db5be/daemonize-2.4.7.tar.gz";
      sha256 = "1j382jbygzhjivg4rbf7i8nn6ybvmhjmi639gin4bgi63234w6f0";
    };
  };
  decorator = super.buildPythonPackage {
    name = "decorator-4.1.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bb/e0/f6e41e9091e130bf16d4437dabbac3993908e4d6485ecbc985ef1352db94/decorator-4.1.2.tar.gz";
      sha256 = "1d8npb11kxyi36mrvjdpcjij76l5zfyrz2f820brf0l0rcw4vdkw";
    };
  };
  enum34 = super.buildPythonPackage {
    name = "enum34-1.1.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz";
      sha256 = "1cgm5ng2gcfrkrm3hc22brl6chdmv67b9zvva9sfs7gn7dwc9n4a";
    };
  };
  frozendict = super.buildPythonPackage {
    name = "frozendict-1.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4e/55/a12ded2c426a4d2bee73f88304c9c08ebbdbadb82569ebdd6a0c007cfd08/frozendict-1.2.tar.gz";
      sha256 = "0ibf1wipidz57giy53dh7mh68f2hz38x8f4wdq88mvxj5pr7jhbp";
    };
  };
  functools32 = super.buildPythonPackage {
    name = "functools32-3.2.3.post2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/5e/1a/0aa2c8195a204a9f51284018562dea77e25511f02fe924fac202fc012172/functools32-3.2.3-2.zip";
      sha256 = "181z816xzb53m98cx24mq9kkm4vmpph9wzsd4cd4531mdjm29n49";
    };
  };
  html5lib = super.buildPythonPackage {
    name = "html5lib-1.0.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six webencodings];
    src = fetchurl {
      url = "https://pypi.python.org/packages/85/3e/cf449cf1b5004e87510b9368e7a5f1acd8831c2d6691edd3c62a0823f98f/html5lib-1.0.1.tar.gz";
      sha256 = "0dipzfrycv6j1jw82v9b7d8lzggx3x8xngx6l4xrqkxwvg7hvjv6";
    };
  };
  hyperlink = super.buildPythonPackage {
    name = "hyperlink-17.3.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/83/df/3bdaf38f21f93429de02f04c6a967d2154955fc5b9a6a1a0b20a682edc13/hyperlink-17.3.1.tar.gz";
      sha256 = "1g1kkj82457l2v5k0qbg6pfq5fkby5agbn3va16j1bdxx6yzskxw";
    };
  };
  idna = super.buildPythonPackage {
    name = "idna-2.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz";
      sha256 = "13qaab6d0s15gknz8v3zbcfmbj6v86hn9pjxgkdf62ch13imssic";
    };
  };
  incremental = super.buildPythonPackage {
    name = "incremental-17.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8f/26/02c4016aa95f45479eea37c90c34f8fab6775732ae62587a874b619ca097/incremental-17.5.0.tar.gz";
      sha256 = "1cylxdz1cnkm5g3pklna3h2n0i0rks95ir1pnpxfnvpkmab1cxbv";
    };
  };
  ipaddress = super.buildPythonPackage {
    name = "ipaddress-1.0.19";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f0/ba/860a4a3e283456d6b7e2ab39ce5cf11a3490ee1a363652ac50abf9f0f5df/ipaddress-1.0.19.tar.gz";
      sha256 = "10agaa1cys1bk1ycpl2w8lky9vjx8h1xh1z29mg0niqx0638c390";
    };
  };
  jinja2 = super.buildPythonPackage {
    name = "jinja2-2.10";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [markupsafe];
    src = fetchurl {
      url = "https://pypi.python.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz";
      sha256 = "190l36hfw3wb2n3n68yacjabxyb1pnxwn7vjx96cmjj002xy2jzq";
    };
  };
  jsonschema = super.buildPythonPackage {
    name = "jsonschema-2.6.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [functools32];
    src = fetchurl {
      url = "https://pypi.python.org/packages/58/b9/171dbb07e18c6346090a37f03c7e74410a1a56123f847efed59af260a298/jsonschema-2.6.0.tar.gz";
      sha256 = "00kf3zmpp9ya4sydffpifn0j0mzm342a2vzh82p6r0vh10cg7xbg";
    };
  };
  ldap3 = super.buildPythonPackage {
    name = "ldap3-2.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pyasn1];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8c/44/19f1d1069cff899a5492d0aa808aef8d4accce8c146ce915cefb29d672db/ldap3-2.4.tar.gz";
      sha256 = "0rky1qp2bl6lsn7hkins3i4h6fsrc4pkibxvhcjqaczb97w1b048";
    };
  };
  markupsafe = super.buildPythonPackage {
    name = "markupsafe-1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz";
      sha256 = "0rdn1s8x9ni7ss8rfiacj7x1085lx8mh2zdwqslnw8xc3l4nkgm6";
    };
  };
  matrix-angular-sdk = super.buildPythonPackage {
    name = "matrix-angular-sdk-0.6.8";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c7/36/d875ee0bfb0f59f6643462b4072f0efaa40e8fe813ab0070a3d7b8963ee0/matrix-angular-sdk-0.6.8.tar.gz";
      sha256 = "0gmx4y5kqqphnq3m7xk2vpzb0w2a4palicw7wfdr1q2schl9fhz2";
    };
  };
  matrix-synapse = super.buildPythonPackage {
    name = "matrix-synapse-0.25.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [matrix-synapse-ldap3 msgpack-python daemonize frozendict psutil pyopenssl pydenticon pymacaroons-pynacl service-identity signedjson pyyaml twisted bleach unpaddedbase64 pillow pyasn1 ujson pynacl netaddr jsonschema blist canonicaljson matrix-angular-sdk jinja2 affinity pysaml2 bcrypt phonenumbers];
    src = ./.;
  };
  matrix-synapse-ldap3 = super.buildPythonPackage {
    name = "matrix-synapse-ldap3-0.1.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [twisted ldap3 service-identity];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ef/9f/313bc9213b84e7a65a740cb6967f49aaa7645d54a96914b55c161eba40d2/matrix-synapse-ldap3-0.1.3.tar.gz";
      sha256 = "0a0d1y9yi0abdkv6chbmxr3vk36gynnqzrjhbg26q4zg06lh9kgn";
    };
  };
  msgpack-python = super.buildPythonPackage {
    name = "msgpack-python-0.4.8";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/21/27/8a1d82041c7a2a51fcc73675875a5f9ea06c2663e02fcfeb708be1d081a0/msgpack-python-0.4.8.tar.gz";
      sha256 = "11pqk5braa6wndpnr1dhg64js82vjgxnm0lzy73rwl831zgijaqs";
    };
  };
  netaddr = super.buildPythonPackage {
    name = "netaddr-0.7.19";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0c/13/7cbb180b52201c07c796243eeff4c256b053656da5cfe3916c3f5b57b3a0/netaddr-0.7.19.tar.gz";
      sha256 = "1zdfadvpq4lmcqzr383gywxn4xyn355kj1n3lk9q2l03vmyfrbiq";
    };
  };
  olefile = super.buildPythonPackage {
    name = "olefile-0.44";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/35/17/c15d41d5a8f8b98cc3df25eb00c5cee76193114c78e5674df6ef4ac92647/olefile-0.44.zip";
      sha256 = "1bbk1xplmrhymqpk6rkb15sg7v9qfih7zh23p6g2fxxas06cmwk1";
    };
  };
  paste = super.buildPythonPackage {
    name = "paste-2.0.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/30/c3/5c2f7c7a02e4f58d4454353fa1c32c94f79fa4e36d07a67c0ac295ea369e/Paste-2.0.3.tar.gz";
      sha256 = "062jk0nlxf6lb2wwj6zc20rlvrwsnikpkh90y0dn8cjch93s6ii3";
    };
  };
  phonenumbers = super.buildPythonPackage {
    name = "phonenumbers-8.8.8";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8d/7a/5908c0d182393ce34892430ef76a145e42fc1065fee06b95c01de5833017/phonenumbers-8.8.8.tar.gz";
      sha256 = "1c2f7ls8qwmw94nc11n5mrysd0w5wq4zwklmhmqvn4n294p4jbzz";
    };
  };
  pillow = super.buildPythonPackage {
    name = "pillow-4.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [olefile];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz";
      sha256 = "09xmn7rl6840sli2iz1k3fgxfgmri2nqz6vkinmb9mgg8ifp2z59";
    };
  };
  psutil = super.buildPythonPackage {
    name = "psutil-5.4.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/54/24/aa854703715fa161110daa001afce75d21d1840e9ab5eb28708d6a5058b0/psutil-5.4.2.tar.gz";
      sha256 = "04gyjj0sgnzkbng36xs4vfpkfygam1zrgmpxgfx5y0qyipzzk880";
    };
  };
  pyasn1 = super.buildPythonPackage {
    name = "pyasn1-0.4.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/eb/3d/b7d0fdf4a882e26674c68c20f40682491377c4db1439870f5b6f862f76ed/pyasn1-0.4.2.tar.gz";
      sha256 = "05bxnr4wmrg62m4qr1pg1p3z7bhwrv74jll3k42pgxwl36kv0n6j";
    };
  };
  pyasn1-modules = super.buildPythonPackage {
    name = "pyasn1-modules-0.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pyasn1];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ab/76/36ab0e099e6bd27ed95b70c2c86c326d3affa59b9b535c63a2f892ac9f45/pyasn1-modules-0.2.1.tar.gz";
      sha256 = "1k3wrlkcwxj9rpmfjvzwi4wzhnmb647wgckmqdyjidi2427yl05g";
    };
  };
  pycparser = super.buildPythonPackage {
    name = "pycparser-2.18";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz";
      sha256 = "09mjyw82ibqzl449g7swy8bfxnfpmas0815d2rkdjlcqw81wma4r";
    };
  };
  pycrypto = super.buildPythonPackage {
    name = "pycrypto-2.6.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz";
      sha256 = "0g0ayql5b9mkjam8hym6zyg6bv77lbh66rv1fyvgqb17kfc1xkpj";
    };
  };
  pydenticon = super.buildPythonPackage {
    name = "pydenticon-0.3.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pillow];
    src = fetchurl {
      url = "https://pypi.python.org/packages/76/fa/3085252e2cfd8353624142fb18ca007a2ce4fe199a1440ea3c85ec5b8620/pydenticon-0.3.1.tar.gz";
      sha256 = "1wbp3crdywnya7gbnh311xbq8s734xh4hmr2wqy1kw7lsv6n7wrf";
    };
  };
  pymacaroons-pynacl = super.buildPythonPackage {
    name = "pymacaroons-pynacl-0.9.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six pynacl];
    src = fetchurl {
      url = "https://github.com/matrix-org/pymacaroons/archive/3068b8537eb3aa85abbb3cc5861289af3d45fdff.tar.gz";
      sha256 = "0qz1fs8r9241lqja1d29g4vv353a1yh7qywl0gd1d6l8w59jq1ix";
    };
  };
  pynacl = super.buildPythonPackage {
    name = "pynacl-0.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [cffi six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1a/a1/752a313b753e694c1efa2657143e734fe3fd8368a55bff1cc3afce47a4c7/PyNaCl-0.3.0.tar.gz";
      sha256 = "1hknxlp3a3f8njn19w92p8nhzl9jkfwzhv5fmxhmyq2m8hqrfj8j";
    };
  };
  pyopenssl = super.buildPythonPackage {
    name = "pyopenssl-17.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [cryptography six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/3b/15/a5d90ab1a41075e8f0fae334f13452549528f82142b3b9d0c9d86ab7178c/pyOpenSSL-17.5.0.tar.gz";
      sha256 = "0wv78mwsdqbxqwdwllf4maqybhbj3vb8328ia04hnb558sxcy41c";
    };
  };
  pysaml2 = super.buildPythonPackage {
    name = "pysaml2-3.0.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [decorator requests paste zope.interface repoze.who pycrypto pytz pyopenssl python-dateutil six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a0/c6/71f2944e8d192f700c28793c6522e1adcf844330f910b4c9dba5e282bb4d/pysaml2-3.0.2.tar.gz";
      sha256 = "0y2iw1dddcvi13xjh3l52z1mvnrbc41ik9k4nn7lwj8x5kimnk9n";
    };
  };
  python-dateutil = super.buildPythonPackage {
    name = "python-dateutil-2.6.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/54/bb/f1db86504f7a49e1d9b9301531181b00a1c7325dc85a29160ee3eaa73a54/python-dateutil-2.6.1.tar.gz";
      sha256 = "1jkahssf0ir5ssxc3ydbp8cpv77limn8d4s77szb2nrgl2r3h749";
    };
  };
  pytz = super.buildPythonPackage {
    name = "pytz-2017.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/60/88/d3152c234da4b2a1f7a989f89609ea488225eaea015bc16fbde2b3fdfefa/pytz-2017.3.zip";
      sha256 = "1dw5l527vcafvdqq4wadwl7ikhb2sssz0v0cssibh8890kyczr7s";
    };
  };
  pyyaml = super.buildPythonPackage {
    name = "pyyaml-3.12";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz";
      sha256 = "1aqjl8dk9amd4zr99n8v2qxzgmr2hdvqfma4zh7a41rj6336c9sr";
    };
  };
  repoze.who = super.buildPythonPackage {
    name = "repoze.who-2.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [webob zope.interface setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/19/ae/94cdd6ea2d3f79a1430993ee044da1ea6fb547675e0d0ca958c71009ddde/repoze.who-2.3.tar.gz";
      sha256 = "0a7axy1sc320a7pjvlj69dvnj9imn77jk9hm06ambk1a4k0sspdr";
    };
  };
  requests = super.buildPythonPackage {
    name = "requests-2.18.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [chardet idna urllib3 certifi];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz";
      sha256 = "0zi3v9nsmv9j27d0c0m1dvqyvaxz53g8m0aa1h3qanxs4irkwi4w";
    };
  };
  service-identity = super.buildPythonPackage {
    name = "service-identity-17.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [attrs pyasn1 pyasn1-modules pyopenssl];
    src = fetchurl {
      url = "https://pypi.python.org/packages/de/2a/cab6e30be82c8fcd2339ef618036720eda954cf05daef514e386661c9221/service_identity-17.0.0.tar.gz";
      sha256 = "1aq24cn3nnsjr9g797dayhx4g653h6bd41ksqhidzq0rvarzn0a0";
    };
  };
  setuptools = super.buildPythonPackage {
    name = "setuptools-38.2.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e9/c3/5986db56819bd88e1a250cad2a97249211686b1b7b5d95f9ab64d403a2cb/setuptools-38.2.5.zip";
      sha256 = "01s5r41b9laqa3qw1gm7knpjykf1dkhcw0rc1da711l6rivg505h";
    };
  };
  signedjson = super.buildPythonPackage {
    name = "signedjson-1.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [canonicaljson unpaddedbase64 pynacl];
    src = fetchurl {
      url = "https://github.com/matrix-org/python-signedjson/archive/3ee65545a4c92ed7719f3c9e9ad53aead8461411.tar.gz";
      sha256 = "0db7jfg81qmb9kglwii68a3px3f40pyfwb90xwymxhpsmkxfr6d5";
    };
  };
  simplejson = super.buildPythonPackage {
    name = "simplejson-3.13.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0d/3f/3a16847fe5c010110a8f54dd8fe7b091b4e22922def374fe1cce9c1cb7e9/simplejson-3.13.2.tar.gz";
      sha256 = "02jg5nixffqyicfqdl4dil82fh1z9p2as758wp0nqwalw0hcykjc";
    };
  };
  six = super.buildPythonPackage {
    name = "six-1.11.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  twisted = super.buildPythonPackage {
    name = "twisted-17.9.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [zope.interface constantly incremental automat hyperlink];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a2/37/298f9547606c45d75aa9792369302cc63aa4bbcf7b5f607560180dd099d2/Twisted-17.9.0.tar.bz2";
      sha256 = "0p7pbb02aff69rjvhm91ha1brczynmq8k5y7r5xy7jjzbpisg88d";
    };
  };
  ujson = super.buildPythonPackage {
    name = "ujson-1.35";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz";
      sha256 = "11jz5wi7mbgqcsz52iqhpyykiaasila4lq8cmc2d54bfa3jp6q7n";
    };
  };
  unpaddedbase64 = super.buildPythonPackage {
    name = "unpaddedbase64-1.1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://github.com/matrix-org/python-unpaddedbase64/archive/c804b5753f4805cf3d129fa4e7febef5c032b6ca.tar.gz";
      sha256 = "07gxfnyzf6pi7cl6xhcdagz4vpcbbqx398xzh3zjpnwbp487dlhl";
    };
  };
  urllib3 = super.buildPythonPackage {
    name = "urllib3-1.22";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz";
      sha256 = "0kyvc9zdlxr5r96bng5rhm9a6sfqidrbvvkz64s76qs5267dli6c";
    };
  };
  webencodings = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  webob = super.buildPythonPackage {
    name = "webob-1.7.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/75/34/731e23f52371852dfe7490a61644826ba7fe70fd52a377aaca0f4956ba7f/WebOb-1.7.4.tar.gz";
      sha256 = "1na01ljg04z40il7vcrn8g29vaw7nvg1xvhk64cr4jys5wcay44d";
    };
  };
  zope.interface = super.buildPythonPackage {
    name = "zope.interface-4.4.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/bd/d2/25349ed41f9dcff7b3baf87bd88a4c82396cf6e02f1f42bb68657a3132af/zope.interface-4.4.3.tar.gz";
      sha256 = "1kn5lldn5xpy2qlzfhf06zddms29z61cp3wka98wcq7xzdfnvlnn";
    };
  };

### Test requirements

  
}
